name: Clear Repo

on:
  workflow_dispatch:

jobs:
  clear-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@master
        with:
          ref: main
      - name: Set Git User
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - name: Clear Repo
        run: |
          git checkout --orphan new-main
          git add -A
          git commit -am "Initial commit"
          git branch -D main
          git branch -m main
          git push -f origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  clear-action-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Delete workflow runs
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.event.repository.name }}"
          RUNS=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/$OWNER/$REPO/actions/runs" | jq -r '.workflow_runs[].id')
          for run in $RUNS; do
            curl -X DELETE -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/$OWNER/$REPO/actions/runs/$run"
          done