name: 'Get Account ID'
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      CF_API_EMAIL: ${{ secrets.CF_API_EMAIL }}
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Python script
      run: python account-id.py